@startuml
skinparam backgroundColor transparent
skinparam ActivityBackgroundColor #eaebff
skinparam ActivityBorderColor #7497a6
skinparam ActivityFontColor black

|이미지 처리|
start
:고해상도 이미지 입력;
:128x128 저해상도 변환 및 정규화;
|객체 인식 및 분류|
:YOLOv5로 표지판 검출;
if (표지판 검출?) then (yes)
  :Bounding Box 좌표 추출;
  :Bounding Box 좌표를 고해상도 원본 이미지에 매핑;
  :고해상도 이미지에서 표지판 영역 크롭;
  :크롭된 영역을 128x128 저해상도로 변환;
  :Custom CNN으로 표지판 분류;
  :속도 제한 값 추출;

else (no)
  :다음 프레임으로;
endif
|속도 제어|
if (속도 제한 표지판 검출?) then (yes)
  :최대 속도 갱신;
else (no)
  :최대 속도 유지;
endif
:현재 속도 확인;
if (속도 초과) then (yes)
  :현재 속도 제한;
else (no)
  :현재 속도 유지;
endif
:다음 프레임 처리;
stop
@enduml